
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class TicTacToaGame extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToaGame
     */
    int turn =2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int powon[]={0,0,0,0,0,0,0,0,0};
    private Object b2;
    
    int pXwon(){
        if(pXwon[0]==1 && pXwon[1]==1&& pXwon[2]==1){
            return 1;
        }
         if(pXwon[3]==1 && pXwon[4]==1&& pXwon[5]==1){
            return 1;
        }
          if(pXwon[6]==1 && pXwon[7]==1&& pXwon[8]==1){
            return 1;
        }
           if(pXwon[0]==1 && pXwon[3]==1&& pXwon[6]==1){
            return 1;
        } if(pXwon[1]==1 && pXwon[4]==1&& pXwon[7]==1){
            return 1;
        }
         if(pXwon[2]==1 && pXwon[5]==1&& pXwon[8]==1){
            return 1;
        }
          if(pXwon[2]==1 && pXwon[4]==1&& pXwon[6]==1){
            return 1;
        }
           if(pXwon[0]==1 && pXwon[4]==1&& pXwon[8]==1){
            return 1;
        }
            return 0;
    }
    
    
        int powon(){
        if(powon[0]==1 && powon[1]==1&& powon[2]==1){
            return 1;
        }
         if(powon[3]==1 && powon[4]==1&& powon[5]==1){
            return 1;
        }
          if(powon[6]==1 && powon[7]==1&& powon[8]==1){
            return 1;
        }
           if(powon[0]==1 && powon[3]==1&& powon[6]==1){
            return 1;
        } if(powon[1]==1 && powon[4]==1&& powon[7]==1){
            return 1;
        }
         if(powon[2]==1 && powon[5]==1&& powon[8]==1){
            return 1;
        }
          if(powon[2]==1 && powon[4]==1&& powon[6]==1){
            return 1;
        }
           if(powon[0]==1 && powon[4]==1&& powon[8]==1){
            return 1;
        }
            return 0;
    }
    public TicTacToaGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        B8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 0, 204));
        reset.setText("Play Again");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("          Tic Tac Toa ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
         if(buttonused[0]==0)
        {
        if(turn%2==0){
            turn++;
            B1.setText("X");
            buttonused[0]=1;
            pXwon[0]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B1.setText("o");
              buttonused[0]=1;
              powon[0]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
         if(buttonused[2]==0)
        {
        if(turn%2==0){
            turn++;
            B2.setText("X");
            buttonused[2]=1;
            pXwon[2]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B2.setText("o");
              buttonused[2]=1;
              powon[2]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        if(buttonused[3]==0)
        {
        if(turn%2==0){
            turn++;
            B3.setText("X");
            buttonused[3]=1;
            pXwon[3]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B3.setText("o");
              buttonused[3]=1;
              powon[3]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
          if(buttonused[4]==0)
        {
        if(turn%2==0){
            turn++;
            B4.setText("X");
            buttonused[4]=1;
            pXwon[4]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B1.setText("o");
              buttonused[0]=1;
              powon[0]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        if(buttonused[5]==0)
        {
        if(turn%2==0){
            turn++;
            B5.setText("X");
            buttonused[5]=1;
            pXwon[5]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B5.setText("o");
              buttonused[5]=1;
              powon[5]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
                                
                                    
                                 

                                       
        
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
         if(buttonused[6]==0)
        {
        if(turn%2==0){
            turn++;
            B6.setText("X");
            buttonused[6]=1;
            pXwon[6]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B6.setText("o");
              buttonused[6]=1;
              powon[6]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(buttonused[7]==0)
        {
        if(turn%2==0){
            turn++;
            b7.setText("X");
            buttonused[7]=1;
            pXwon[7]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            b7.setText("o");
              buttonused[7]=1;
              powon[7]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_b7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
          if(buttonused[8]==0)
        {
        if(turn%2==0){
            turn++;
            B8.setText("X");
            buttonused[8]=1;
            pXwon[8]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B8.setText("o");
              buttonused[8]=1;
              powon[8]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
                             
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
         if(buttonused[0]==0)
        {
        if(turn%2==0){
            turn++;
            B9.setText("X");
            buttonused[9]=1;
            pXwon[9]=1;
            
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        else{
            turn++;
            B9.setText("o");
              buttonused[9]=1;
              powon[9]=1;
               
            int result1=pXwon();
            int result2=powon();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
            }else if(result2==1){
                 JOptionPane.showMessageDialog(rootPane, "Player o won!!!");
            }
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane,"This Button is already Used!!!");
                }
    }//GEN-LAST:event_B9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        B1.setText("");
        B2.setText("");
        B3.setText("");
        B4.setText("");
        B5.setText("");
        B6.setText("");
        b7.setText("");
        B8.setText("");
        B9.setText("");
        turn=2;
        for(int i=0;i<9;i++){
            buttonused[i]=0;
        }
         for(int i=0;i<9;i++){
            pXwon[i]=0;
        }
          for(int i=0;i<9;i++){
            powon[i]=0;
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToaGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton b7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
